### ISSUE TITLE
gold ?

### ISSUE THREAD

**Issue by fengmingfeng** [gokulkarthik/hateclipper#2]
1.the differance between disablity_pc and disablity_gold_pc ?
2.pc is protected chariacter ?
3.what is the gold ?gold?
4.the differance between gold_attack and attack?

**Comment by gokulkarthik** [comment]
Please check https://github.com/facebookresearch/fine_grained_hateful_memes and https://arxiv.org/pdf/2005.04790.pdf for more details on the dataset. If you find the code useful, please star the repository.
